---
- name: Install R1soft Server
  become: yes
  become_method: sudo
  user: centos
  hosts: server
  tasks:
  - name: Create repo
    copy:
      src: r1soft.repo
      dest: /etc/yum.repos.d/
    ignore_errors: true
  - name: Install server
    package:
      name: r1soft-cdp-enterprise-server
      state: present
  - name: Create user and password
    command: "r1soft-setup  --user admin --pass redhat --http-port 8080"
  - name: Start server
    command: "/etc/init.d/cdp-server start"